### ISSUE TITLE
Image url path

### ISSUE THREAD

**Issue by haxinc** [RoshanNindrai/RBImagePickerController#4]
Hi

Can i get the asset-url path after image selected ?

Thanks

**Comment by RoshanNindrai** [comment]
HI sorry for the late reply. I am assuming that you need the url of the image instead of the actual image. This makes sense if u want to select more images and that the array can be passed around.

**Comment by haxinc** [comment]
@RoshanNindrai Np, take your time and thanks for replying

**Comment by RoshanNindrai** [comment]
@haxinc Hi, I have deprecated the previous delegate method that returns UIImage objects, since its not lightweight. The new delegate method returns the Asset urls, which can be used to get hold of the assets using AssetLibrary (https://developer.apple.com/library/ios/documentation/AssetsLibrary/Reference/ALAssetsLibrary_Class/Reference/Reference.html#//apple_ref/doc/uid/TP40009722-CH1-SW7). I am closing this issue.
